Allow Lumen Publishing
laravel-doctrine/migrations pull request #60
Opened 2018-02-12 16:48 UTC by ragboyjr

Allow publishing of the config files for lumen.

Publishing is easily enabled in lumen by just adding the VendorPublishCommand. However, this check currently prevents the publishing even though it works fine on lumen.

Signed-off-by: RJ Garcia <rj@bighead.net>

2018-02-15 04:45 UTC, ragboyjr commented
ping

2018-02-22 03:19 UTC, ragboyjr commented
ping

2018-02-27 11:45 UTC, patrickbrouwers requested changes

2018-02-27 11:45 UTC, patrickbrouwers commented on src/MigrationsServiceProvider.php
> +            $this->getConfigPath() => config_path('migrations.php'),
This won't work on a clean Lumen install, as it doesn't know the `config_path` helper.

2018-02-27 11:46 UTC, patrickbrouwers commented
No need to ping, it's pretty annoying. I pick up stuff whenever I have time for it. Pinging will only have the opposite effect.

Can you look at the comment, please.

2018-02-27 15:10 UTC, ragboyjr commented
@patrickbrouwers didn't mean to annoy you. I get a flood of emails every day it feels like, sometimes, I see a Github notification but then forget about it that day.

I'm closing this because the laravel foundation/helpers conflict with the lumen helpers. When I first tried this, the lumen helpers loaded first, but when used composer install from a fresh install, laravel's went first and it broke the system. So unfortunately you can't have laravel/framework installed with lumen :(.

Thank you by the way for taking the time to make this package and review the code. It's been very helpful in my projects.

2018-02-27 15:10 UTC, closed without merging

2018-02-27 15:30 UTC, patrickbrouwers commented
@ragboyjr thanks for understanding!